In [1]:
import pandas as pd

# Reading Data


In [2]:
df = pd.read_csv('data.csv');

In [3]:
df.head()

fever  bpain  age  runnyNose  diffBreadth  infProb
0  101.749837      0   54          0           -1        0
1  100.954371      0   32          0            1        1
2  101.632166      1   19          1           -1        1
3  100.333615      0   76          1           -1        1
4  101.628520      0   16          1            0        0

In [4]:
df.tail()


fever  bpain  age  runnyNose  diffBreadth  infProb
2510  98.563832      0   43          1            0        0
2511  99.235207      1   85          1            1        0
2512  99.051927      0   26          1           -1        0
2513  98.880346      1   42          1            0        1
2514  98.434946      0   14          1           -1        1

In [5]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2515 entries, 0 to 2514
Data columns (total 6 columns):
fever          2515 non-null float64
bpain          2515 non-null int64
age            2515 non-null int64
runnyNose      2515 non-null int64
diffBreadth    2515 non-null int64
infProb        2515 non-null int64
dtypes: float64(1), int64(5)
memory usage: 118.0 KB


In [6]:
df['diffBreadth'].value_counts()

-1    875
 0    840
 1    800
Name: diffBreadth, dtype: int64

In [7]:
df.describe()

fever       bpain          age    runnyNose  diffBreadth  \
count  2515.000000  2515.00000  2515.000000  2515.000000  2515.000000   
mean    100.015994     0.47833    50.323658     0.498211    -0.029821   
std       1.145234     0.49963    29.143000     0.500096     0.815708   
min      98.000083     0.00000     1.000000     0.000000    -1.000000   
25%      99.022039     0.00000    24.500000     0.000000    -1.000000   
50%     100.015177     0.00000    50.000000     0.000000     0.000000   
75%     101.014756     1.00000    75.000000     1.000000     1.000000   
max     101.997393     1.00000   100.000000     1.000000     1.000000   

           infProb  
count  2515.000000  
mean      0.506958  
std       0.500051  
min       0.000000  
25%       0.000000  
50%       1.000000  
75%       1.000000  
max       1.000000

# Train test Splititng

In [8]:
import numpy as np

In [9]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data)*ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]



In [10]:
np.random.permutation(7)

array([0, 5, 1, 3, 4, 6, 2])

In [11]:
train, test = data_split(df,0.2)

In [12]:
train


fever  bpain  age  runnyNose  diffBreadth  infProb
2461   99.022512      1   39          1            1        0
2284  101.497736      1   33          1            1        1
289    98.246014      0   37          0            0        1
2031  100.347659      0   24          0           -1        0
2254  100.403508      0   53          1           -1        0
...          ...    ...  ...        ...          ...      ...
1638   98.488138      0   58          1           -1        0
1095   98.444924      1   23          0            1        1
1130  101.009359      0    9          1            1        1
1294  100.720599      0   71          1            1        0
860   100.667023      0   88          0           -1        1

[2012 rows x 6 columns]

In [13]:
test


fever  bpain  age  runnyNose  diffBreadth  infProb
617   100.377820      1   20          0           -1        0
927    99.183079      1   61          0            0        0
942   100.612163      0   76          0            0        0
973    99.489929      1   42          0            0        0
1967  101.289220      1   99          1            1        0
...          ...    ...  ...        ...          ...      ...
1011   98.493489      0  100          1            0        1
51    100.758381      0   18          0            0        0
1935   98.954548      1    1          1           -1        0
495    98.763519      1   13          1           -1        0
1467  100.792510      0   98          0           -1        0

[503 rows x 6 columns]

In [14]:
<<

In [15]:
x_train

array([[ 99.02251248,   1.        ,  39.        ,   1.        ,
          1.        ],
       [101.4977355 ,   1.        ,  33.        ,   1.        ,
          1.        ],
       [ 98.24601446,   0.        ,  37.        ,   0.        ,
          0.        ],
       ...,
       [101.0093589 ,   0.        ,   9.        ,   1.        ,
          1.        ],
       [100.7205989 ,   0.        ,  71.        ,   1.        ,
          1.        ],
       [100.6670231 ,   0.        ,  88.        ,   0.        ,
         -1.        ]])

In [16]:
x_test = test[['fever','bpain','age','runnyNose','diffBreadth']].to_numpy()

In [17]:
x_test


array([[100.3778196 ,   1.        ,  20.        ,   0.        ,
         -1.        ],
       [ 99.18307892,   1.        ,  61.        ,   0.        ,
          0.        ],
       [100.6121632 ,   0.        ,  76.        ,   0.        ,
          0.        ],
       ...,
       [ 98.95454821,   1.        ,   1.        ,   1.        ,
         -1.        ],
       [ 98.76351896,   1.        ,  13.        ,   1.        ,
         -1.        ],
       [100.7925098 ,   0.        ,  98.        ,   0.        ,
         -1.        ]])

In [18]:
y_train =  train[['infProb']].to_numpy().reshape(2012,)
y_test =  test[['infProb']].to_numpy().reshape(503,)

In [19]:
y_train

array([0, 1, 1, ..., 1, 0, 1])

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
clf = LogisticRegression()
clf.fit(x_train,y_train)

/home/soham/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [27]:
inputfeatures = [102,1,22,1,0]
infProbint = clf.predict([inputfeatures])

In [28]:
infProb = clf.predict_proba([inputfeatures])

In [29]:
infProbint

array([0])

In [30]:
infProb

array([[0.50094872, 0.49905128]])

In [31]:
    infProb[0][1]

0.49905127638776714